CREATE DATABASE auth;
CREATE DATABASE earth;
CREATE DATABASE mars;

GRANT ALL PRIVILEGES ON DATABASE auth TO postgres;
GRANT ALL PRIVILEGES ON DATABASE earth TO postgres;
GRANT ALL PRIVILEGES ON DATABASE mars TO postgres;
